<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="XOR-BSA-39" failures="5" tests="5" name="Default test(failed)(failed)" time="56.393" errors="0" timestamp="2022-11-21T23:49:21 IST">
  <testcase classname="TestNGPractice.DataProvider_Practice" name="verifyUser" time="10.305">
    <failure type="java.lang.AssertionError" message="login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at TestNGPractice.DataProvider_Practice.verifyUser(DataProvider_Practice.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyUser -->
  <testcase classname="TestNGPractice.DataProvider_Practice" name="verifyUser" time="10.284">
    <failure type="java.lang.AssertionError" message="login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at TestNGPractice.DataProvider_Practice.verifyUser(DataProvider_Practice.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyUser -->
  <testcase classname="TestNGPractice.DataProvider_Practice" name="verifyUser" time="10.209">
    <failure type="java.lang.AssertionError" message="login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at TestNGPractice.DataProvider_Practice.verifyUser(DataProvider_Practice.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyUser -->
  <testcase classname="TestNGPractice.DataProvider_Practice" name="verifyUser" time="10.23">
    <failure type="java.lang.AssertionError" message="login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at TestNGPractice.DataProvider_Practice.verifyUser(DataProvider_Practice.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyUser -->
  <testcase classname="TestNGPractice.DataProvider_Practice" name="verifyUser" time="10.241">
    <failure type="java.lang.AssertionError" message="login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: login unsuccessful expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at TestNGPractice.DataProvider_Practice.verifyUser(DataProvider_Practice.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifyUser -->
</testsuite> <!-- Default test(failed)(failed) -->
